# Generated by Django 2.2.5 on 2019-09-10 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TextImporter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_order', models.IntegerField(unique=True)),
                ('posting_period', models.IntegerField()),
                ('fiscal_year', models.IntegerField()),
                ('customer', models.IntegerField()),
                ('bill_document', models.IntegerField()),
                ('file', models.FileField(upload_to='files')),
            ],
        ),
    ]
