# Generated by Django 2.2.5 on 2019-09-10 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_importer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textimporter',
            name='file',
        ),
    ]
