# Generated by Django 2.2.5 on 2019-09-10 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_importer', '0002_remove_textimporter_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='textimporter',
            name='files',
            field=models.FileField(null=True, upload_to='media'),
        ),
    ]
